FROM golang:1.25.1 AS builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o producer main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/producer .
EXPOSE 8080
ENTRYPOINT ["/app/producer"]

